package lk.lumina;
import jakarta.servlet.*;import jakarta.servlet.annotation.*;import java.nio.file.*;import java.sql.*;import java.time.*;import java.util.*;import java.util.concurrent.*;
import org.apache.pdfbox.pdmodel.*;import org.apache.pdfbox.pdmodel.font.*;
@WebListener public class Bootstrap implements ServletContextListener{
 private ScheduledExecutorService timer;
 public void contextInitialized(ServletContextEvent event){try{DB.init();schema();Migrations.run();seed();DemoFixtures.seed();BookReferences.initialize();indexes();timer=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"lumina-reminders");t.setDaemon(true);return t;});timer.scheduleWithFixedDelay(()->{try{Library.reminders();Mail.deliver();}catch(Exception e){event.getServletContext().log("Reminder/email processing failed; will retry",e);}},15,60,TimeUnit.SECONDS);}catch(Exception e){throw new IllegalStateException("Lumina could not start. Check database and storage configuration.",e);}}
 public void contextDestroyed(ServletContextEvent event){if(timer!=null)timer.shutdownNow();DB.close();}
 public static void schema()throws Exception{String schema=new String(Bootstrap.class.getResourceAsStream("/schema.sql").readAllBytes(),java.nio.charset.StandardCharsets.UTF_8);try(Connection c=DB.connection()){for(String sql:schema.split(";")){if(sql.isBlank())continue;String table=sql.trim().split(" ")[2];boolean exists=false;try(ResultSet r=c.getMetaData().getTables(c.getCatalog(),c.getSchema(),null,new String[]{"TABLE"})){while(r.next())if(table.equalsIgnoreCase(r.getString("TABLE_NAME")))exists=true;}if(!exists)try(Statement s=c.createStatement()){s.execute(sql);}}}}

 public static void indexes()throws Exception{try(Connection c=DB.connection()){String[][] indexes={{"loans","ix_loans_access","user_id,kind,status,due_at"},{"payments","ix_payments_owner","user_id,status"},{"notifications","ix_notifications_unread","user_id,is_read,id"},{"copies","ix_copies_availability","book_id,branch_id,status"},{"reservations","ix_reservations_queue","status,book_id,branch_id,id"},{"books","ix_books_category","active,category_id"}};for(String[] index:indexes){boolean exists=false;try(ResultSet rs=c.getMetaData().getIndexInfo(c.getCatalog(),c.getSchema(),index[0],false,false)){while(rs.next())if(index[1].equalsIgnoreCase(rs.getString("INDEX_NAME")))exists=true;}if(!exists)try(Statement s=c.createStatement()){s.execute("CREATE INDEX "+index[1]+" ON "+index[0]+"("+index[2]+")");}}}}
 public static void seed()throws Exception{
  if(DB.one("SELECT * FROM users")!=null){return;}
  DB.tx(c->{var now=Timestamp.from(Instant.now());long branch=DB.update(c,"INSERT INTO branches(name,address,phone,hours) VALUES(?,?,?,?)","Lumina Central","Colombo Â· Main reading room","011 555 0180","Monâ€“Sat 8:30 amâ€“6:00 pm");
   DB.update(c,"INSERT INTO branches(name,address,phone,hours) VALUES(?,?,?,?)","The Garden Branch","Kandy Â· Garden reading room","081 555 0180","Monâ€“Sat 9:00 amâ€“5:00 pm");
   String pass=Security.hash(Config.get("bootstrap.password","Lumina@2026!"));
   for(String role:List.of("ADMIN","LIBRARIAN","BRANCH_MANAGER","MANAGEMENT","READER")){String user=role.toLowerCase(Locale.ROOT);DB.update(c,"INSERT INTO users(name,email,username,password_hash,phone,address,role,branch_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)",role.equals("READER")?"Demo Reader":"Lumina "+role.replace('_',' '),user+"@lumina.test",user,pass,"0770000000","Colombo",role,branch,now);}
   String[] cats={"Literature","Science & nature","History","Technology","Art & philosophy","Travel"};for(String cat:cats)DB.update(c,"INSERT INTO categories(name,description) VALUES(?,?)",cat,"Explore the "+cat.toLowerCase()+" collection.");
   DB.update(c,"INSERT INTO publishers(name,description) VALUES(?,?)","Lumina Editions","Original demonstration reading material.");
   String[] authors={"Lumina Editorial","The Reading Room","Lumina Field Notes"};for(String a:authors)DB.update(c,"INSERT INTO authors(name,description) VALUES(?,?)",a,"The Lumina original sample collection.");
   String[] titles={"The Art of Paying Attention","A Field Guide to Wonder","Letters from the Old World","Thinking in Systems","The Quiet Architecture","Beyond the Familiar"};
   String[] desc={"An invitation to slow down, look closer, and rediscover the remarkable in everyday life.","Follow the patterns of the natural world, from the smallest leaf to the widest night sky.","A reading-room journey through memory, archives, and the stories we choose to preserve.","A thoughtful introduction to connections, feedback, and the structures behind everyday decisions.","Explore the relationship between space, stillness, and the art of making room for thought.","Notes on curiosity, new places, and finding another way to see the world."};
   Files.createDirectories(Config.data().resolve("pdf"));Files.createDirectories(Config.data().resolve("covers"));
   for(int i=0;i<titles.length;i++){String file="sample-"+(i+1)+".pdf";long book=DB.update(c,"INSERT INTO books(isbn,title,author_id,category_id,publisher_id,description,publication_year,edition,format,pdf_path,fee,duration_days,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)","LUM-000"+(i+1),titles[i],(i%3)+1,i+1,1,desc[i],2026,"First edition","PHYSICAL",null,0,14,now);for(int j=0;j<3;j++)DB.update(c,"INSERT INTO copies(book_id,branch_id) VALUES(?,?)",book,j==2?2:1);}
   DB.update(c,"INSERT INTO suppliers(name,email,phone,address) VALUES(?,?,?,?)","Lumina Book Supply","supply@example.test","0115550190","Colombo");
   for(String[] pair:new String[][]{{"physical_days","14"},{"max_loans","5"},{"fine_per_day","20"},{"reservation_hours","48"}})if(DB.one(c,"SELECT setting_key FROM settings WHERE setting_key=?",pair[0])==null)DB.update(c,"INSERT INTO settings(setting_key,setting_value) VALUES(?,?)",pair[0],pair[1]);
   for(var u:DB.list(c,"SELECT id FROM users"))Library.notify(c,DB.id(u,"id"),"Welcome to Lumina","Your reading room is ready. Explore the collection and make yourself at home.","/catalog","welcome-"+u.get("id"));return null;});
 }

}
