<%@ page pageEncoding="UTF-8" %>
<%@ include file="header.jspf" %>

<%var payment=(Map<String,Object>)request.getAttribute("payment");%><section class="section checkout-layout"><div class="checkout-story"><span class="eyebrow">ONE STEP CLOSER TO YOUR NEXT CHAPTER</span><h1>A little anticipation.<br><em>A wonderful read.</em></h1><div class="checkout-steps"><span>01 Select book</span><strong>02 Confirm payment</strong><span>03 Start reading</span></div><div class="checkout-illustration"><img class="book-object" src="<%=ctx%><%=payment.get("book_id")==null?"/assets/cover-1.svg":"/cover?id="+payment.get("book_id")%>" alt="Book cover"><span>&#10022;</span></div></div><div class="panel checkout-card"><span class="eyebrow">YOUR ORDER</span><h2><%=payment.get("title")==null?"Fine payment":ViewUtils.e(payment.get("title"))%></h2><dl class="order-lines"><div><dt>Reference</dt><dd>#<%=payment.get("id")%></dd></div><%if(payment.get("book_id")!=null){%><div><dt>Digital borrowing</dt><dd><%=payment.get("duration_days")%> days</dd></div><%}%><div><dt>Status</dt><dd><%=ViewUtils.e(payment.get("status"))%></dd></div><div class="order-total"><dt>Total</dt><dd><%=ViewUtils.money(payment.get("amount"))%></dd></div></dl><%if(payment.get("status").equals("PENDING")){%><form method="post" action="<%=ctx%>/checkout" data-checkout-form><input type="hidden" name="csrf" value="<%=csrf%>"><input type="hidden" name="id" value="<%=payment.get("id")%>"><fieldset class="card-options"><legend>Choose your card</legend><label class="card-choice"><input type="radio" name="card_method" value="VISA" checked required><span class="visa-word">VISA</span><small>Credit / debit</small></label><label class="card-choice"><input type="radio" name="card_method" value="MASTER" required><span class="master-symbol" aria-hidden="true"></span><span>Mastercard</span></label></fieldset><%if(AppConfig.demo()){%><fieldset class="demo-card-details"><legend>Card details</legend>
<p class="micro">Practice details only. Nothing entered here is sent or saved.</p>
<label for="demo-holder">Name on card<input id="demo-holder" autocomplete="off" required maxlength="80" placeholder="Name as shown on card"></label>
<label for="demo-number">Card number<input id="demo-number" type="text" inputmode="numeric" autocomplete="off" required minlength="16" maxlength="19" pattern="[0-9]{4} ?[0-9]{4} ?[0-9]{4} ?[0-9]{4}" placeholder="1234 5678 9012 3456" aria-describedby="card-number-help" data-demo-number></label>
<small id="card-number-help" class="card-hint" aria-live="polite">0 / 16 digits</small>
<div class="card-detail-row"><label for="demo-expiry">Expiry date<input id="demo-expiry" placeholder="MM/YY" inputmode="numeric" autocomplete="off" required maxlength="5" pattern="(0[1-9]|1[0-2])/[0-9]{2}" data-demo-expiry></label>
<label for="demo-cvv">CVV<input id="demo-cvv" type="password" inputmode="numeric" autocomplete="off" required minlength="3" maxlength="3" pattern="[0-9]{3}" placeholder="123"></label></div>
</fieldset><div class="notice"><strong>Demonstration checkout</strong><p>Card details are checked only in this page. No money is charged. Use sample details to try borrowing and PDF access.</p></div><button class="button full" name="outcome" value="success">Confirm demo payment &#8594;</button><button class="text-button" name="outcome" value="fail">Test a failed payment</button><%}else{%><div class="secure-note"><span aria-hidden="true">&#128274;</span><p>Enter your card number, valid expiry date and CVV on PayHereâ€™s secure checkout. Your bank verifies the payment.</p></div><label>Phone number<input name="phone" required maxlength="40" value="<%=ViewUtils.e(user.get("phone"))%>"></label><label>Billing address<input name="address" required maxlength="500" value="<%=ViewUtils.e(user.get("address"))%>"></label><label>City<input name="city" required maxlength="120"></label><button class="button full">Pay securely by card &#8594;</button><p class="micro">You will enter card details on PayHere's secure payment page.<%=AppConfig.get("payment.mode","demo").equals("payhere-sandbox")?" Sandbox mode: test cards only.":""%></p><%}%></form><%}else{%><a class="button full" href="<%=ctx%>/payment-status?id=<%=payment.get("id")%>">View payment result</a><%}%><%if(payment.get("status").equals("PENDING")){%><form method="post" action="<%=ctx%>/action" data-confirm="Cancel this pending payment order?"><input type="hidden" name="csrf" value="<%=csrf%>"><input type="hidden" name="action" value="cancel-payment"><input type="hidden" name="id" value="<%=payment.get("id")%>"><button class="text-button">Cancel pending order</button></form><%}%><p class="micro">Reading access begins after the payment is verified.</p></div></section>

<%@ include file="footer.jspf" %>
