<%@ page pageEncoding="UTF-8" %>
<%@ include file="header.jspf" %>
<section class="module-hero">
 <div class="hero-copy"><span class="eyebrow">YOUR LIBRARY, THOUGHTFULLY ORGANISED</span><h1><%=Web.e(ModuleAccess.TITLE)%><span class="hero-period">.</span></h1><p><%=Web.e(ModuleAccess.DESCRIPTION)%></p><div class="hero-actions"><%String primary="/login";if(user!=null){primary="/catalog";for(String[] link:ModuleAccess.LINKS)if(ModuleAccess.linkVisible(link[1],user)){primary=link[1];break;}}%><a class="button" href="<%=ctx%><%=primary%>"><%=user==null?"Sign in to get started":"Open workspace"%> &#8594;</a><a class="button ghost" href="<%=ctx%>/catalog">Explore books</a></div><div class="hero-note"><span class="status-dot"></span> A little order. A world of possibility.</div></div>
 <div class="hero-photo"><img src="<%=ctx%>/assets/library.webp" alt="Warmly lit library shelves" width="1920" height="1080"><div class="photo-caption"><span>THE LUMINA LIBRARY</span><strong>Room to discover.<br>Space to grow.</strong></div></div>
</section>
<%if(manager){%><section class="module-stats" aria-label="Library statistics"><%for(String[] stat:ModuleAccess.STATS){var count=DB.one("SELECT COUNT(*) AS n FROM "+stat[1]);%><article><span><%=Web.e(stat[0])%></span><strong><%=count.get("n")%></strong><small>In this library</small></article><%}%></section><%}%>
<section class="section module-tools"><div class="section-heading"><div><span class="eyebrow">EVERYTHING YOU NEED</span><h2>Your library workspace</h2></div><p>Simple tools. Clear records. Better library service.</p></div><div class="tool-grid"><%int tool=0;for(String[] link:ModuleAccess.LINKS){if(user==null||ModuleAccess.linkVisible(link[1],user)){tool++;%><a class="tool-card" href="<%=ctx%><%=user==null?"/login":link[1]%>"><span class="tool-icon"><%=String.format("%02d",tool)%></span><h3><%=Web.e(link[0])%></h3><p>Open and manage your <%=Web.e(link[0].toLowerCase())%>.</p><span class="tool-arrow" aria-hidden="true">&#8599;</span></a><%}}if(tool==0){%><a class="tool-card" href="<%=ctx%>/catalog"><span class="tool-icon">01</span><h3>Discover the collection</h3><p>Search titles and check book availability.</p><span class="tool-arrow" aria-hidden="true">&#8599;</span></a><%}%></div></section>
<section class="section home-bottom"><div><span class="eyebrow">CONNECTED BY CURIOSITY</span><h2>A place for every chapter.</h2><p>Find a title, discover an author and see what is available at your library.</p></div><form method="get" action="<%=ctx%>/catalog" class="home-search"><label for="home-query">Find your next book</label><div><input id="home-query" name="q" type="search" placeholder="Search by title, ISBN or author"><button class="button">Search &#8594;</button></div></form></section>
<%@ include file="footer.jspf" %>
