<%@ page pageEncoding="UTF-8" %>
<%@ include file="header.jspf" %>
<%var payment=(Map<String,Object>)request.getAttribute("payment");boolean demo="DEMO".equals(payment.get("provider"));%>
<section class="section receipt-section">
<div class="receipt-caption"><span class="eyebrow">A LITTLE MOMENT. A NEW CHAPTER.</span><span class="paid-badge">&#10003; Paid</span></div>
<article class="receipt" aria-label="Payment receipt">
<div class="receipt-top"><div><span class="brand-text">LUMINA</span><small>THE LIBRARY</small></div><div><span class="eyebrow">PAYMENT RECEIPT</span><strong>LUM-<%=payment.get("id")%></strong></div></div>
<div class="receipt-greeting"><div><h1>Thank you.</h1><p>Your payment has been recorded.</p></div><span class="receipt-seal" aria-hidden="true">&#10003;</span></div>
<%if(demo){%><div class="notice">DEMONSTRATION RECEIPT — NO MONEY CHARGED</div><%}%>
<dl class="order-lines"><div><dt>Receipt</dt><dd>LUM-<%=payment.get("id")%></dd></div><div><dt>Paid by</dt><dd><%=ViewUtils.e(payment.get("name"))%></dd></div><div><dt>Payment date</dt><dd><%=ViewUtils.date(payment.get("paid_at"))%><small>Sri Lanka time</small></dd></div><div><dt>Description</dt><dd><%=payment.get("title")==null?"Library fine":ViewUtils.e(payment.get("title"))%></dd></div>
<%if(payment.get("loan_id")!=null){%><div><dt>Digital borrowing</dt><dd><%=payment.get("duration_days")%> days</dd></div><div><dt>Borrowing starts</dt><dd><%=ViewUtils.date(payment.get("receipt_start"))%></dd></div><div><dt>Borrowing expires</dt><dd><%=ViewUtils.date(payment.get("receipt_due"))%></dd></div><%}%>
<div><dt>Provider / method</dt><dd><%=ViewUtils.e(payment.get("provider"))%> / <%=ViewUtils.e(payment.get("method"))%><%if(payment.get("card_last4")!=null){%><small>Card ending <%=ViewUtils.e(payment.get("card_last4"))%></small><%}%></dd></div><div><dt>Transaction reference</dt><dd><%=ViewUtils.e(payment.get("provider_ref"))%></dd></div><div class="order-total"><dt>Paid</dt><dd><%=ViewUtils.money(payment.get("amount"))%></dd></div></dl>
<p class="receipt-signoff">Lumina Library · A world within reach</p></article>
<div class="receipt-actions"><%if(payment.get("loan_id")!=null){%><a class="button" href="<%=ctx%>/reader?id=<%=payment.get("loan_id")%>">Read Now &#8594;</a><%}%><a class="button ghost" href="<%=ctx%>/receipt?id=<%=payment.get("id")%>&amp;format=pdf">Download Receipt</a><button class="button ghost print-button" data-print>Print / Save as PDF</button></div><a class="form-link" href="<%=ctx%>/payments">Back to payments</a></section>
<%if(Boolean.TRUE.equals(request.getAttribute("celebrate"))){%>
<dialog class="payment-celebration" aria-labelledby="payment-success-title" aria-describedby="payment-success-copy" data-payment-success="<%=payment.get("id")%>"><button type="button" class="success-close" aria-label="Close payment confirmation" data-close-success>&#215;</button><div class="success-particles" aria-hidden="true"><%for(int i=0;i<16;i++){%><i style="--i:<%=i%>"></i><%}%></div><svg class="success-mark" viewBox="0 0 100 100" fill="none" aria-hidden="true"><circle cx="50" cy="50" r="43"/><path d="M29 50 44 65 72 36"/></svg><span class="eyebrow">YOUR NEXT CHAPTER AWAITS</span><h2 id="payment-success-title">Payment Successful</h2><p id="payment-success-copy"><%=payment.get("loan_id")==null?"Your payment has been recorded.":"Your book is ready to read."%></p><strong class="success-amount"><%=ViewUtils.money(payment.get("amount"))%></strong><%if(demo){%><small class="success-demo">Demonstration · No money charged</small><%}%><div class="success-timer" aria-hidden="true"><span></span></div></dialog><div class="sr-only" role="status" aria-live="polite">Payment successful. Your receipt is ready.</div>
<%}%>
<%@ include file="footer.jspf" %>
