package lk.lumina;
import jakarta.servlet.*;import jakarta.servlet.annotation.*;import jakarta.servlet.http.*;
import java.io.*;import java.nio.file.*;import java.sql.*;import java.time.*;import java.util.*;import java.math.*;import java.awt.image.*;import javax.imageio.ImageIO;
@WebServlet(urlPatterns={"/","/action","/api/notifications","/book","/catalog","/cover","/dashboard","/fine","/fines","/home","/login","/logout","/notifications","/payments","/profile","/receipt","/reservations"})
@MultipartConfig(maxFileSize=52428800,maxRequestSize=57671680,fileSizeThreshold=1048576)
public class Web extends HttpServlet{
 private record Attempts(int count,long start){}private static final Map<String,Attempts> attempts=new java.util.concurrent.ConcurrentHashMap<>();
 private static final Set<String> PUBLIC=Set.of("/","/home","/catalog","/book","/login","/signup","/forgot","/reset","/cover","/payment-notify");
 public static final Map<String,String[]> ENTITIES=new LinkedHashMap<>();
 static{}
 public static String e(Object o){return Security.esc(o);}public static String money(Object o){return "LKR "+String.format(Locale.US,"%,.2f",o==null?BigDecimal.ZERO:new BigDecimal(o.toString()));}
 public static String date(Object o){return o==null?"â€”":((Timestamp)o).toInstant().atZone(ZoneId.of("Asia/Colombo")).format(java.time.format.DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm"));}
 public static String text(Map<String,Object> r,String key){return Objects.toString(r.get(key),"");}
 public static boolean staff(Map<String,Object> u){return u!=null&&Set.of("ADMIN","LIBRARIAN").contains(u.get("role"));}
 public static boolean manager(Map<String,Object> u){return staff(u)||u!=null&&Set.of("MANAGEMENT","BRANCH_MANAGER").contains(u.get("role"));}
 private static Long branch(Map<String,Object> u){return u.get("role").equals("BRANCH_MANAGER")?DB.id(u,"branch_id"):null;}
 private static void staffOnly(Map<String,Object> u){Library.require(staff(u),"Staff access required.");}
 private static void adminOnly(Map<String,Object> u){Library.require(u.get("role").equals("ADMIN"),"Administrator access required.");}
 private static String p(HttpServletRequest q,String key){String value=Objects.toString(q.getParameter(key),"");return key.contains("password")?value:value.trim();}
 private static long num(HttpServletRequest q,String key){String v=p(q,key);return v.isBlank()?0:Long.parseLong(v);}
 private static String required(HttpServletRequest q,String key,int max){String v=p(q,key);Library.require(!v.isBlank()&&v.length()<=max,"Please enter a valid "+key.replace('_',' ')+" (maximum "+max+" characters).");return v;}
 private static int positive(HttpServletRequest q,String key,int max){long v=num(q,key);Library.require(v>0&&v<=max,"Invalid "+key.replace('_',' ')+".");return (int)v;}
 private static BigDecimal price(HttpServletRequest q,String key){BigDecimal d=new BigDecimal(p(q,key)).setScale(2,java.math.RoundingMode.HALF_UP);Library.require(d.signum()>=0&&d.compareTo(new BigDecimal("10000000"))<0,"Enter a valid amount.");return d;}
 private static void email(String s){Library.require(s.length()<=180&&s.matches("[^\\s@]+@[^\\s@]+\\.[^\\s@]+"),"Enter a valid email address.");}
 @SuppressWarnings("unchecked") protected void service(HttpServletRequest q,HttpServletResponse r)throws ServletException,IOException{
  q.setCharacterEncoding("UTF-8");r.setCharacterEncoding("UTF-8");r.setHeader("X-Content-Type-Options","nosniff");r.setHeader("Referrer-Policy","same-origin");r.setHeader("X-Frame-Options","SAMEORIGIN");r.setHeader("Cache-Control","no-store");r.setHeader("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; frame-src 'self' blob:; worker-src 'self' blob:; font-src 'self' data: blob:; connect-src 'self'; object-src 'self'; base-uri 'self'; form-action 'self'");
  String path=q.getServletPath();if(path.isEmpty())path="/";q.setAttribute("path",path);q.setAttribute("ctx",q.getContextPath());
  if(path.startsWith("/assets/")&&(q.getMethod().equals("GET")||q.getMethod().equals("HEAD"))){r.setHeader("Cache-Control","public, max-age=86400");getServletContext().getNamedDispatcher("default").forward(q,r);return;}
  try{
   HttpSession s=q.getSession();if(s.getAttribute("csrf")==null)s.setAttribute("csrf",Security.token());Map<String,Object> u=null;if(s.getAttribute("uid")!=null)u=DB.one("SELECT id,name,email,username,phone,address,role,branch_id,active FROM users WHERE id=? AND active=1",s.getAttribute("uid"));q.setAttribute("user",u);
   if(!ModuleAccess.allowed(q,u)){r.setStatus(403);q.setAttribute("problem","This operation is not available in this member project or for your account role.");view(q,r,"error");return;}
   if(!PUBLIC.contains(path)&&u==null){r.sendRedirect(q.getContextPath()+"/login");return;}
   if(q.getMethod().equals("POST")){Library.require(Objects.equals(s.getAttribute("csrf"),p(q,"csrf")),"Your session changed. Refresh the page and try again.");post(q,r,path,u);return;}
   if(!q.getMethod().equals("GET")&&!q.getMethod().equals("HEAD")){r.sendError(405);return;}
   get(q,r,path,u);
  }catch(java.time.format.DateTimeParseException ex){r.setStatus(400);q.setAttribute("problem","Enter a valid date and time.");view(q,r,"error");}catch(java.sql.SQLException ex){getServletContext().log("Database request failed",ex);r.setStatus(400);q.setAttribute("problem",ex.getSQLState()!=null&&ex.getSQLState().startsWith("23")?"This value already exists or is linked to another record. Check the record and try again.":"Database operation failed. Check your database configuration and the runtime/logs folder.");view(q,r,"error");}catch(IllegalArgumentException ex){r.setStatus(400);q.setAttribute("problem",ex.getMessage());view(q,r,"error");}catch(Exception ex){getServletContext().log("Request failed: "+path,ex);r.setStatus(500);q.setAttribute("problem","This action could not be completed. Your saved records are safe. Check the server log for details or try again.");view(q,r,"error");}
 }
 private void view(HttpServletRequest q,HttpServletResponse r,String name)throws ServletException,IOException{r.setContentType("text/html;charset=UTF-8");q.getRequestDispatcher("/WEB-INF/views/"+name+".jsp").forward(q,r);}
 private void go(HttpServletRequest q,HttpServletResponse r,String path,String message)throws IOException{q.getSession().setAttribute("flash",message);r.sendRedirect(q.getContextPath()+path);}
 public static String booksSql(){return "SELECT b.*,a.name AS author,c.name AS category,p.name AS publisher,(SELECT COUNT(*) FROM copies cp WHERE cp.book_id=b.id AND cp.status='AVAILABLE') AS available FROM books b JOIN authors a ON a.id=b.author_id JOIN categories c ON c.id=b.category_id JOIN publishers p ON p.id=b.publisher_id";}
 private void get(HttpServletRequest q,HttpServletResponse r,String path,Map<String,Object> u)throws Exception{
  switch(path){
   case "/":case "/home":q.setAttribute("books",DB.list(booksSql()+" WHERE b.active=1 ORDER BY b.id OFFSET 0 ROWS FETCH NEXT 6 ROWS ONLY"));q.setAttribute("branches",DB.list("SELECT * FROM branches WHERE active=1"));view(q,r,"home");break;
   case "/login":view(q,r,"auth");break;
   case "/catalog":{
    String filter=" WHERE b.active=1";List<Object> args=new ArrayList<>();if(!p(q,"q").isBlank()){filter+=" AND (b.title LIKE ? OR b.isbn LIKE ? OR a.name LIKE ? OR p.name LIKE ?)";for(int i=0;i<4;i++)args.add("%"+p(q,"q")+"%");}if(num(q,"category")>0){filter+=" AND b.category_id=?";args.add(num(q,"category"));}if(Set.of("DIGITAL","PHYSICAL").contains(p(q,"format"))){filter+=" AND b.format IN (?, 'BOTH')";args.add(p(q,"format"));}if(p(q,"available").equals("1"))filter+=" AND (b.pdf_path IS NOT NULL OR EXISTS(SELECT 1 FROM copies x WHERE x.book_id=b.id AND x.status='AVAILABLE'))";if(num(q,"branch")>0){filter+=" AND EXISTS(SELECT 1 FROM copies x WHERE x.book_id=b.id AND x.branch_id=?)";args.add(num(q,"branch"));}
    int page=(int)Math.max(1,Math.min(10000,num(q,"page")));q.setAttribute("page",page);q.setAttribute("total",DB.one("SELECT COUNT(*) AS n FROM books b JOIN authors a ON a.id=b.author_id JOIN publishers p ON p.id=b.publisher_id"+filter,args.toArray()).get("n"));String order=p(q,"sort").equals("title")?"b.title":"b.id DESC";q.setAttribute("books",DB.list(booksSql()+filter+" ORDER BY "+order+" OFFSET "+((page-1)*12)+" ROWS FETCH NEXT 12 ROWS ONLY",args.toArray()));q.setAttribute("categories",DB.list("SELECT * FROM categories WHERE active=1 ORDER BY name"));q.setAttribute("branches",DB.list("SELECT * FROM branches WHERE active=1"));view(q,r,"catalog");break;}
   case "/book":q.setAttribute("book",DB.one(booksSql()+" WHERE b.id=? AND b.active=1",num(q,"id")));Library.require(q.getAttribute("book")!=null,"Book not found.");q.setAttribute("branches",DB.list("SELECT br.*, (SELECT COUNT(*) FROM copies c WHERE c.book_id=? AND c.branch_id=br.id AND c.status='AVAILABLE') AS available FROM branches br WHERE br.active=1",num(q,"id")));view(q,r,"book");break;
   case "/dashboard":view(q,r,"home");break;
   case "/cover":var b=DB.one("SELECT cover_path FROM books WHERE id=?",num(q,"id"));if(b==null||b.get("cover_path")==null){r.sendRedirect(q.getContextPath()+"/assets/cover-"+((Math.max(1,num(q,"id"))-1)%6+1)+".svg");return;}r.setHeader("Cache-Control","public, max-age=0, must-revalidate");String etag="\""+b.get("cover_path")+"\"";r.setHeader("ETag",etag);if(etag.equals(q.getHeader("If-None-Match"))){r.setStatus(304);return;}file(q,r,Config.data().resolve("covers"),b.get("cover_path").toString(),"image/jpeg");break;
   case "/payments":q.setAttribute("rows",DB.list("SELECT p.id,p.order_ref,b.title,p.amount,p.provider,p.method,p.status,p.created_at,p.paid_at FROM payments p LEFT JOIN books b ON b.id=p.book_id WHERE p.user_id=? ORDER BY p.id DESC",u.get("id")));view(q,r,"payments");break;
   case "/receipt":var receipt=DB.one("SELECT p.*,COALESCE(p.receipt_name,u.name) AS name,COALESCE(p.receipt_email,u.email) AS email,COALESCE(p.receipt_title,b.title) AS title,COALESCE(p.receipt_isbn,b.isbn) AS isbn FROM payments p JOIN users u ON u.id=p.user_id LEFT JOIN books b ON b.id=p.book_id WHERE p.id=? AND p.status='SUCCESSFUL' AND "+(staff(u)?(u.get("role").equals("ADMIN")?"1=1":"EXISTS (SELECT 1 FROM fines f JOIN loans l ON l.id=f.loan_id JOIN copies cp ON cp.id=l.copy_id WHERE f.id=p.fine_id"+(branch(u)==null?"":" AND cp.branch_id="+branch(u))+")"):"p.user_id="+u.get("id")),num(q,"id"));Library.require(receipt!=null,"Receipt unavailable.");q.setAttribute("payment",receipt);if(p(q,"format").equals("pdf")){r.setContentType("application/pdf");r.setHeader("Content-Disposition","attachment; filename=\"Lumina-Receipt-"+receipt.get("id")+".pdf\"");Receipts.pdf(receipt,r.getOutputStream());}else view(q,r,"receipt");break;
   case "/api/notifications":r.setContentType("application/json");var n=DB.one("SELECT COUNT(*) AS n,COALESCE(MAX(id),0) AS latest FROM notifications WHERE user_id=? AND is_read=0",u.get("id"));r.getWriter().write("{\"unread\":"+n.get("n")+",\"latest\":"+n.get("latest")+"}");break;
   case "/notifications":q.setAttribute("rows",DB.list("SELECT TOP 100 * FROM notifications WHERE user_id=? ORDER BY id DESC",u.get("id")));view(q,r,"notifications");break;
   case "/reservations":q.setAttribute("branches",DB.list("SELECT * FROM branches WHERE active=1"+(branch(u)==null?"":" AND id="+branch(u))));q.setAttribute("rows",DB.list("SELECT r.*,b.title,u.name,br.name AS branch FROM reservations r JOIN books b ON b.id=r.book_id JOIN users u ON u.id=r.user_id JOIN branches br ON br.id=r.branch_id WHERE "+(staff(u)?(branch(u)==null?"1=1":"r.branch_id="+branch(u)):"r.user_id="+u.get("id"))+" ORDER BY r.id DESC"));view(q,r,"reservations");break;
   case "/fine":var fineDetail=DB.one("SELECT f.*,u.name,b.title,cp.branch_id FROM fines f JOIN users u ON u.id=f.user_id JOIN loans l ON l.id=f.loan_id JOIN books b ON b.id=l.book_id JOIN copies cp ON cp.id=l.copy_id WHERE f.id=?",num(q,"id"));Library.require(fineDetail!=null&&(staff(u)||DB.id(fineDetail,"user_id")==DB.id(u,"id")),"Fine unavailable.");if(staff(u))Workflows.scope(fineDetail,branch(u));q.setAttribute("fine",fineDetail);q.setAttribute("rows",DB.list("SELECT id,amount,method,provider,provider_ref,status,created_at,paid_at FROM payments WHERE fine_id=? ORDER BY id DESC",num(q,"id")));view(q,r,"fine");break;
   case "/fines":q.setAttribute("rows",DB.list("SELECT f.*,u.name,b.title,(f.amount-(SELECT COALESCE(SUM(pay.amount),0) FROM payments pay WHERE pay.fine_id=f.id AND pay.status='SUCCESSFUL')) AS balance FROM fines f JOIN users u ON u.id=f.user_id JOIN loans l ON l.id=f.loan_id JOIN books b ON b.id=l.book_id WHERE "+(staff(u)?(branch(u)==null?"1=1":"l.copy_id IN (SELECT id FROM copies WHERE branch_id="+branch(u)+")"):"f.user_id="+u.get("id"))+" ORDER BY f.id DESC"));view(q,r,"fines");break;
   case "/profile":view(q,r,"profile");break;
   default:r.sendError(404);
  }
 }
 private void post(HttpServletRequest q,HttpServletResponse r,String path,Map<String,Object> u)throws Exception{
  if(path.equals("/login")){String key=q.getRemoteAddr()+":"+p(q,"username").toLowerCase(Locale.ROOT);long now=System.currentTimeMillis();attempts.entrySet().removeIf(x->now-x.getValue().start>900000);Attempts a=attempts.getOrDefault(key,new Attempts(0,now));Library.require(a.count<8,"Too many attempts. Try again after 15 minutes.");attempts.put(key,new Attempts(a.count+1,a.start));var account=DB.one("SELECT * FROM users WHERE (username=? OR email=?) AND active=1",p(q,"username").toLowerCase(Locale.ROOT),p(q,"username").toLowerCase(Locale.ROOT));Library.require(account!=null&&Security.verify(p(q,"password"),account.get("password_hash").toString()),"The username or password is incorrect.");attempts.remove(key);DB.tx(c->{Library.audit(c,DB.id(account,"id"),"Login","Successful sign in");return null;});q.changeSessionId();q.getSession().setAttribute("csrf",Security.token());q.getSession().setAttribute("uid",account.get("id"));go(q,r,"/home","Welcome back to Lumina.");return;}
  Library.require(u!=null,"Please sign in.");long uid=DB.id(u,"id");
  if(path.equals("/logout")){q.getSession().invalidate();r.sendRedirect(q.getContextPath()+"/home");return;}
  if(path.equals("/profile")){if(p(q,"operation").equals("password")){var row=DB.one("SELECT password_hash FROM users WHERE id=?",uid);Library.require(Security.verify(p(q,"current_password"),row.get("password_hash").toString()),"Current password is incorrect.");Security.password(p(q,"password"));Library.require(p(q,"password").equals(p(q,"confirm_password")),"Passwords do not match.");DB.update("UPDATE users SET password_hash=? WHERE id=?",Security.hash(p(q,"password")),uid);}else DB.update("UPDATE users SET name=?,phone=?,address=? WHERE id=?",required(q,"name",180),required(q,"phone",40),required(q,"address",500),uid);go(q,r,"/profile","Your account has been updated.");return;}
  Library.require(path.equals("/action"),"Unknown action.");String action=p(q,"action");switch(action){
   case "reserve":Library.reserve(uid,num(q,"book_id"),num(q,"branch_id"));go(q,r,"/reservations","Reservation saved. Watch your notifications for collection details.");return;
   case "cancel-reservation":Library.cancelReservation(uid,num(q,"id"),staff(u),branch(u));go(q,r,"/reservations","Reservation cancelled.");return;
   case "read-notifications":DB.update("UPDATE notifications SET is_read=1 WHERE user_id=?"+(num(q,"id")>0?" AND id="+num(q,"id"):""),uid);go(q,r,"/notifications","Notifications marked as read.");return;
   case "payment-correct":case "payment-void":staffOnly(u);long correctionId=num(q,"id");String correctionReason=required(q,"reason",500);long fineId=DB.tx(c->{var pay=DB.one(c,"SELECT p.*,cp.branch_id FROM payments p JOIN fines f ON f.id=p.fine_id JOIN loans l ON l.id=f.loan_id JOIN copies cp ON cp.id=l.copy_id WHERE p.id=? AND p.provider='OFFLINE' AND p.status='SUCCESSFUL'",correctionId);Workflows.scope(pay,branch(u));if(action.equals("payment-void")){DB.update(c,"UPDATE payments SET status='REFUNDED',provider_ref=? WHERE id=?",correctionReason.substring(0,Math.min(120,correctionReason.length())),correctionId);Workflows.fineStatus(c,DB.id(pay,"fine_id"));}else{String method=p(q,"method");Library.require(Set.of("CASH","BANK_TRANSFER","OTHER_OFFLINE").contains(method),"Invalid offline method.");DB.update(c,"UPDATE payments SET method=?,provider_ref=? WHERE id=?",method,p(q,"reference"),correctionId);}Library.audit(c,uid,action,"Payment "+correctionId+": "+correctionReason);return DB.id(pay,"fine_id");});go(q,r,"/fine?id="+fineId,"Payment record corrected. No money was transferred.");return;
   case "offline-fine":staffOnly(u);Workflows.offlinePayment(uid,num(q,"id"),price(q,"amount"),p(q,"method"),p(q,"reference"),branch(u));go(q,r,"/fines","Payment recorded and balance updated.");return;
   case "reservation-edit":Workflows.moveReservation(uid,num(q,"id"),num(q,"branch_id"),staff(u),branch(u));go(q,r,"/reservations","Collection branch updated; queue time restarted.");return;
   case "reserve-member":staffOnly(u);Library.reserve(num(q,"user_id"),num(q,"book_id"),branch(u)==null?num(q,"branch_id"):branch(u));go(q,r,"/reservations","Reservation created for member.");return;
   case "assess-fines":staffOnly(u);Workflows.assessOverdue(uid,branch(u));go(q,r,"/fines","Overdue fines assessed without duplicate records.");return;
   case "adjust-fine":case "void-fine":staffOnly(u);Workflows.adjustFine(uid,num(q,"id"),action.equals("void-fine")?BigDecimal.ZERO:price(q,"amount"),required(q,"reason",500),branch(u),action.equals("void-fine"));go(q,r,"/fines","Fine correction recorded.");return;
   default:throw new IllegalArgumentException("Unknown action.");
  }
 }
 private void file(HttpServletRequest q,HttpServletResponse r,Path folder,String name,String mime)throws Exception{Path path=folder.resolve(name).normalize();Library.require(path.startsWith(folder.normalize())&&Files.isRegularFile(path),"File is unavailable. Ask the library to replace it.");long size=Files.size(path),start=0,end=size-1;String range=q.getHeader("Range");if(range!=null&&range.matches("bytes=\\d+-\\d*")){String[] parts=range.substring(6).split("-",-1);start=Long.parseLong(parts[0]);if(!parts[1].isBlank())end=Math.min(end,Long.parseLong(parts[1]));if(start>end||start>=size){r.setStatus(416);r.setHeader("Content-Range","bytes */"+size);return;}r.setStatus(206);r.setHeader("Content-Range","bytes "+start+"-"+end+"/"+size);}r.setContentType(mime);r.setHeader("Accept-Ranges","bytes");r.setHeader("Content-Disposition","inline; filename=\""+(mime.equals("application/pdf")?"lumina-book.pdf":"cover.jpg")+"\"");r.setContentLengthLong(end-start+1);if(q.getMethod().equals("HEAD"))return;try(RandomAccessFile f=new RandomAccessFile(path.toFile(),"r")){f.seek(start);byte[] buf=new byte[32768];long left=end-start+1;while(left>0){int n=f.read(buf,0,(int)Math.min(buf.length,left));if(n<0)break;r.getOutputStream().write(buf,0,n);left-=n;}}}
}
