<%@ page pageEncoding="UTF-8" %>
<%@ include file="header.jspf" %>
<section class="module-auth"><aside><span class="eyebrow">WELCOME TO LUMINA</span><h1>A little order.<br>A world of<br><em>possibility.</em></h1><p><%=Web.e(ModuleAccess.TITLE)%></p><img src="<%=ctx%>/assets/library.webp" alt="Library shelves"></aside><div class="panel auth-panel">
<%boolean signup=current.equals("/signup"),forgot=current.equals("/forgot"),reset=current.equals("/reset");%><span class="eyebrow">YOUR LIBRARY ACCOUNT</span><h2><%=signup?"Join the library":forgot?"Reset your password":reset?"Choose a new password":"Welcome back"%></h2><p><%=signup?"Create your member account.":forgot?"Enter the email address on your account.":reset?"Use a strong password for your account.":"Sign in to open your library workspace."%></p>
<form method="post" action="<%=ctx%><%=current.equals("/login")?"/login":current%>"><input type="hidden" name="csrf" value="<%=csrf%>">
<%if(signup){for(String field:List.of("name","email","username","phone","address")){%><label><%=field.substring(0,1).toUpperCase()+field.substring(1)%><input name="<%=field%>" type="<%=field.equals("email")?"email":"text"%>" required maxlength="<%=field.equals("address")?500:field.equals("phone")||field.equals("username")?40:180%>"></label><%}}else if(forgot){%><label>Email address<input type="email" name="email" required maxlength="180"></label><%}else if(!reset){%><label>Username or email<input name="username" required autocomplete="username" maxlength="180" autofocus></label><%}%>
<%if(!forgot){%><label><%=reset?"New password":"Password"%><input type="password" name="password" required autocomplete="<%=signup||reset?"new-password":"current-password"%>" <%=signup||reset?"minlength=\"10\"":""%> maxlength="128"></label><%if(signup||reset){%><label>Confirm password<input type="password" name="confirm_password" required minlength="10" maxlength="128" autocomplete="new-password"></label><p class="micro">At least 10 characters, with uppercase, lowercase, a number and a symbol.</p><%}}if(reset){%><input type="hidden" name="token" value="<%=Web.e(request.getParameter("token"))%>"><%}%>
<button class="button" type="submit"><%=signup?"Create account":forgot?"Request reset":reset?"Save new password":"Sign in"%> &#8594;</button></form>
<%if(ModuleAccess.is("users")){%><div class="auth-links"><a href="<%=ctx%>/login">Sign in</a><a href="<%=ctx%>/signup">Create account</a><a href="<%=ctx%>/forgot">Forgot password?</a></div><%if(session.getAttribute("devReset")!=null){%><div class="notice">Local demo reset link: <a href="<%=Web.e(session.getAttribute("devReset"))%>">Choose a new password</a></div><%session.removeAttribute("devReset");}}%>
<%if(Config.get("db.mode","demo").equals("demo")&&current.equals("/login")){%><div class="demo-hint"><strong>Local demonstration</strong><p>Username: <code>admin</code><br>Password: <code>Lumina@2026!</code></p><small>Use the reader account to view member permissions.</small></div><%}%>
</div></section>
<%@ include file="footer.jspf" %>
