package lk.lumina;
import jakarta.servlet.*;import jakarta.servlet.annotation.*;import jakarta.servlet.http.*;
import java.io.*;import java.nio.file.*;import java.sql.*;import java.time.*;import java.util.*;import java.math.*;import java.awt.image.*;import javax.imageio.ImageIO;
@WebServlet(urlPatterns={"/","/action","/api/notifications","/book","/book-edit","/catalog","/cover","/dashboard","/home","/login","/logout","/manage","/notifications","/profile"})
@MultipartConfig(maxFileSize=52428800,maxRequestSize=57671680,fileSizeThreshold=1048576)
public class Web extends HttpServlet{
 private record Attempts(int count,long start){}private static final Map<String,Attempts> attempts=new java.util.concurrent.ConcurrentHashMap<>();
 private static final Set<String> PUBLIC=Set.of("/","/home","/catalog","/book","/login","/signup","/forgot","/reset","/cover","/payment-notify");
 public static final Map<String,String[]> ENTITIES=new LinkedHashMap<>();
 static{}
 public static String e(Object o){return Security.esc(o);}public static String money(Object o){return "LKR "+String.format(Locale.US,"%,.2f",o==null?BigDecimal.ZERO:new BigDecimal(o.toString()));}
 public static String date(Object o){return o==null?"â€”":((Timestamp)o).toInstant().atZone(ZoneId.of("Asia/Colombo")).format(java.time.format.DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm"));}
 public static String text(Map<String,Object> r,String key){return Objects.toString(r.get(key),"");}
 public static boolean staff(Map<String,Object> u){return u!=null&&Set.of("ADMIN","LIBRARIAN").contains(u.get("role"));}
 public static boolean manager(Map<String,Object> u){return staff(u)||u!=null&&Set.of("MANAGEMENT","BRANCH_MANAGER").contains(u.get("role"));}
 private static Long branch(Map<String,Object> u){return u.get("role").equals("BRANCH_MANAGER")?DB.id(u,"branch_id"):null;}
 private static void staffOnly(Map<String,Object> u){Library.require(staff(u),"Staff access required.");}
 private static void adminOnly(Map<String,Object> u){Library.require(u.get("role").equals("ADMIN"),"Administrator access required.");}
 private static String p(HttpServletRequest q,String key){String value=Objects.toString(q.getParameter(key),"");return key.contains("password")?value:value.trim();}
 private static long num(HttpServletRequest q,String key){String v=p(q,key);return v.isBlank()?0:Long.parseLong(v);}
 private static String required(HttpServletRequest q,String key,int max){String v=p(q,key);Library.require(!v.isBlank()&&v.length()<=max,"Please enter a valid "+key.replace('_',' ')+" (maximum "+max+" characters).");return v;}
 private static int positive(HttpServletRequest q,String key,int max){long v=num(q,key);Library.require(v>0&&v<=max,"Invalid "+key.replace('_',' ')+".");return (int)v;}
 private static BigDecimal price(HttpServletRequest q,String key){BigDecimal d=new BigDecimal(p(q,key)).setScale(2,java.math.RoundingMode.HALF_UP);Library.require(d.signum()>=0&&d.compareTo(new BigDecimal("10000000"))<0,"Enter a valid amount.");return d;}
 private static void email(String s){Library.require(s.length()<=180&&s.matches("[^\\s@]+@[^\\s@]+\\.[^\\s@]+"),"Enter a valid email address.");}
 @SuppressWarnings("unchecked") protected void service(HttpServletRequest q,HttpServletResponse r)throws ServletException,IOException{
  q.setCharacterEncoding("UTF-8");r.setCharacterEncoding("UTF-8");r.setHeader("X-Content-Type-Options","nosniff");r.setHeader("Referrer-Policy","same-origin");r.setHeader("X-Frame-Options","SAMEORIGIN");r.setHeader("Cache-Control","no-store");r.setHeader("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; frame-src 'self' blob:; worker-src 'self' blob:; font-src 'self' data: blob:; connect-src 'self'; object-src 'self'; base-uri 'self'; form-action 'self'");
  String path=q.getServletPath();if(path.isEmpty())path="/";q.setAttribute("path",path);q.setAttribute("ctx",q.getContextPath());
  if(path.startsWith("/assets/")&&(q.getMethod().equals("GET")||q.getMethod().equals("HEAD"))){r.setHeader("Cache-Control","public, max-age=86400");getServletContext().getNamedDispatcher("default").forward(q,r);return;}
  try{
   HttpSession s=q.getSession();if(s.getAttribute("csrf")==null)s.setAttribute("csrf",Security.token());Map<String,Object> u=null;if(s.getAttribute("uid")!=null)u=DB.one("SELECT id,name,email,username,phone,address,role,branch_id,active FROM users WHERE id=? AND active=1",s.getAttribute("uid"));q.setAttribute("user",u);
   if(!ModuleAccess.allowed(q,u)){r.setStatus(403);q.setAttribute("problem","This operation is not available in this member project or for your account role.");view(q,r,"error");return;}
   if(!PUBLIC.contains(path)&&u==null){r.sendRedirect(q.getContextPath()+"/login");return;}
   if(q.getMethod().equals("POST")){Library.require(Objects.equals(s.getAttribute("csrf"),p(q,"csrf")),"Your session changed. Refresh the page and try again.");post(q,r,path,u);return;}
   if(!q.getMethod().equals("GET")&&!q.getMethod().equals("HEAD")){r.sendError(405);return;}
   get(q,r,path,u);
  }catch(java.time.format.DateTimeParseException ex){r.setStatus(400);q.setAttribute("problem","Enter a valid date and time.");view(q,r,"error");}catch(java.sql.SQLException ex){getServletContext().log("Database request failed",ex);r.setStatus(400);q.setAttribute("problem",ex.getSQLState()!=null&&ex.getSQLState().startsWith("23")?"This value already exists or is linked to another record. Check the record and try again.":"Database operation failed. Check your database configuration and the runtime/logs folder.");view(q,r,"error");}catch(IllegalArgumentException ex){r.setStatus(400);q.setAttribute("problem",ex.getMessage());view(q,r,"error");}catch(Exception ex){getServletContext().log("Request failed: "+path,ex);r.setStatus(500);q.setAttribute("problem","This action could not be completed. Your saved records are safe. Check the server log for details or try again.");view(q,r,"error");}
 }
 private void view(HttpServletRequest q,HttpServletResponse r,String name)throws ServletException,IOException{r.setContentType("text/html;charset=UTF-8");q.getRequestDispatcher("/WEB-INF/views/"+name+".jsp").forward(q,r);}
 private void go(HttpServletRequest q,HttpServletResponse r,String path,String message)throws IOException{q.getSession().setAttribute("flash",message);r.sendRedirect(q.getContextPath()+path);}
 public static String booksSql(){return "SELECT b.*,a.name AS author,c.name AS category,p.name AS publisher,(SELECT COUNT(*) FROM copies cp WHERE cp.book_id=b.id AND cp.status='AVAILABLE') AS available FROM books b JOIN authors a ON a.id=b.author_id JOIN categories c ON c.id=b.category_id JOIN publishers p ON p.id=b.publisher_id";}
 private void get(HttpServletRequest q,HttpServletResponse r,String path,Map<String,Object> u)throws Exception{
  switch(path){
   case "/":case "/home":q.setAttribute("books",DB.list(booksSql()+" WHERE b.active=1 ORDER BY b.id OFFSET 0 ROWS FETCH NEXT 6 ROWS ONLY"));q.setAttribute("branches",DB.list("SELECT * FROM branches WHERE active=1"));view(q,r,"home");break;
   case "/login":view(q,r,"auth");break;
   case "/catalog":{
    String filter=" WHERE b.active=1";List<Object> args=new ArrayList<>();if(!p(q,"q").isBlank()){filter+=" AND (b.title LIKE ? OR b.isbn LIKE ? OR a.name LIKE ? OR p.name LIKE ?)";for(int i=0;i<4;i++)args.add("%"+p(q,"q")+"%");}if(num(q,"category")>0){filter+=" AND b.category_id=?";args.add(num(q,"category"));}if(Set.of("DIGITAL","PHYSICAL").contains(p(q,"format"))){filter+=" AND b.format IN (?, 'BOTH')";args.add(p(q,"format"));}if(p(q,"available").equals("1"))filter+=" AND (b.pdf_path IS NOT NULL OR EXISTS(SELECT 1 FROM copies x WHERE x.book_id=b.id AND x.status='AVAILABLE'))";if(num(q,"branch")>0){filter+=" AND EXISTS(SELECT 1 FROM copies x WHERE x.book_id=b.id AND x.branch_id=?)";args.add(num(q,"branch"));}
    int page=(int)Math.max(1,Math.min(10000,num(q,"page")));q.setAttribute("page",page);q.setAttribute("total",DB.one("SELECT COUNT(*) AS n FROM books b JOIN authors a ON a.id=b.author_id JOIN publishers p ON p.id=b.publisher_id"+filter,args.toArray()).get("n"));String order=p(q,"sort").equals("title")?"b.title":"b.id DESC";q.setAttribute("books",DB.list(booksSql()+filter+" ORDER BY "+order+" OFFSET "+((page-1)*12)+" ROWS FETCH NEXT 12 ROWS ONLY",args.toArray()));q.setAttribute("categories",DB.list("SELECT * FROM categories WHERE active=1 ORDER BY name"));q.setAttribute("branches",DB.list("SELECT * FROM branches WHERE active=1"));view(q,r,"catalog");break;}
   case "/book":q.setAttribute("book",DB.one(booksSql()+" WHERE b.id=? AND b.active=1",num(q,"id")));Library.require(q.getAttribute("book")!=null,"Book not found.");q.setAttribute("branches",DB.list("SELECT br.*, (SELECT COUNT(*) FROM copies c WHERE c.book_id=? AND c.branch_id=br.id AND c.status='AVAILABLE') AS available FROM branches br WHERE br.active=1",num(q,"id")));view(q,r,"book");break;
   case "/dashboard":view(q,r,"home");break;
   case "/cover":var b=DB.one("SELECT cover_path FROM books WHERE id=?",num(q,"id"));if(b==null||b.get("cover_path")==null){r.sendRedirect(q.getContextPath()+"/assets/cover-"+((Math.max(1,num(q,"id"))-1)%6+1)+".svg");return;}r.setHeader("Cache-Control","public, max-age=0, must-revalidate");String etag="\""+b.get("cover_path")+"\"";r.setHeader("ETag",etag);if(etag.equals(q.getHeader("If-None-Match"))){r.setStatus(304);return;}file(q,r,Config.data().resolve("covers"),b.get("cover_path").toString(),"image/jpeg");break;
   case "/api/notifications":r.setContentType("application/json");var n=DB.one("SELECT COUNT(*) AS n,COALESCE(MAX(id),0) AS latest FROM notifications WHERE user_id=? AND is_read=0",u.get("id"));r.getWriter().write("{\"unread\":"+n.get("n")+",\"latest\":"+n.get("latest")+"}");break;
   case "/notifications":q.setAttribute("rows",DB.list("SELECT TOP 100 * FROM notifications WHERE user_id=? ORDER BY id DESC",u.get("id")));view(q,r,"notifications");break;
   case "/profile":view(q,r,"profile");break;
   case "/manage":staffOnly(u);manage(q,u);view(q,r,"manage");break;
   case "/book-edit":staffOnly(u);q.setAttribute("book",num(q,"id")>0?DB.one("SELECT * FROM books WHERE id=?",num(q,"id")):null);for(String t:List.of("authors","publishers","categories","branches"))q.setAttribute(t,DB.list("SELECT * FROM "+t+" WHERE active=1 ORDER BY name"));view(q,r,"book-edit");break;
   default:r.sendError(404);
  }
 }
 private void manage(HttpServletRequest q,Map<String,Object> u)throws Exception{String entity=p(q,"entity");if(entity.isBlank())entity="books";Library.require(ENTITIES.containsKey(entity)||Set.of("books","users","purchases","copies").contains(entity),"Unknown workspace.");if(entity.equals("users")||entity.equals("branches"))adminOnly(u);q.setAttribute("entity",entity);
  String sql=entity.equals("books")?"SELECT b.id,b.title,b.isbn,b.format,b.active FROM books b":entity.equals("users")?"SELECT id,name,email,username,phone,address,member_type,role,branch_id,active FROM users":entity.equals("copies")?"SELECT c.id,b.title,c.book_id,c.branch_id,c.shelf,c.status FROM copies c JOIN books b ON b.id=c.book_id"+(branch(u)==null?"":" WHERE c.branch_id="+branch(u)):entity.equals("purchases")?"SELECT p.id,s.name AS supplier,b.title,p.supplier_id,p.book_id,p.branch_id,p.quantity,p.received_quantity,p.unit_cost,p.invoice_ref,p.notes,p.status,p.created_at FROM purchases p JOIN suppliers s ON s.id=p.supplier_id JOIN books b ON b.id=p.book_id"+(branch(u)==null?"":" WHERE p.branch_id="+branch(u)):"SELECT * FROM "+entity;
  q.setAttribute("rows",DB.list(sql+" ORDER BY id DESC"));if(num(q,"edit")>0&&ENTITIES.containsKey(entity))q.setAttribute("editing",DB.one("SELECT * FROM "+entity+" WHERE id=?",num(q,"edit")));if(num(q,"edit")>0&&entity.equals("users"))q.setAttribute("editing",DB.one("SELECT id,name,email,username,phone,address,member_type,role,branch_id,active FROM users WHERE id=?",num(q,"edit")));
  if(Set.of("purchases","copies","users").contains(entity)){q.setAttribute("books",DB.list("SELECT id,title FROM books WHERE active=1 AND format<>'DIGITAL'"));q.setAttribute("branches",DB.list("SELECT * FROM branches WHERE active=1"+(branch(u)==null?"":" AND id="+branch(u))));q.setAttribute("suppliers",DB.list("SELECT * FROM suppliers WHERE active=1"));}
 }
 private void post(HttpServletRequest q,HttpServletResponse r,String path,Map<String,Object> u)throws Exception{
  if(path.equals("/login")){String key=q.getRemoteAddr()+":"+p(q,"username").toLowerCase(Locale.ROOT);long now=System.currentTimeMillis();attempts.entrySet().removeIf(x->now-x.getValue().start>900000);Attempts a=attempts.getOrDefault(key,new Attempts(0,now));Library.require(a.count<8,"Too many attempts. Try again after 15 minutes.");attempts.put(key,new Attempts(a.count+1,a.start));var account=DB.one("SELECT * FROM users WHERE (username=? OR email=?) AND active=1",p(q,"username").toLowerCase(Locale.ROOT),p(q,"username").toLowerCase(Locale.ROOT));Library.require(account!=null&&Security.verify(p(q,"password"),account.get("password_hash").toString()),"The username or password is incorrect.");attempts.remove(key);DB.tx(c->{Library.audit(c,DB.id(account,"id"),"Login","Successful sign in");return null;});q.changeSessionId();q.getSession().setAttribute("csrf",Security.token());q.getSession().setAttribute("uid",account.get("id"));go(q,r,"/home","Welcome back to Lumina.");return;}
  Library.require(u!=null,"Please sign in.");long uid=DB.id(u,"id");
  if(path.equals("/logout")){q.getSession().invalidate();r.sendRedirect(q.getContextPath()+"/home");return;}
  if(path.equals("/profile")){if(p(q,"operation").equals("password")){var row=DB.one("SELECT password_hash FROM users WHERE id=?",uid);Library.require(Security.verify(p(q,"current_password"),row.get("password_hash").toString()),"Current password is incorrect.");Security.password(p(q,"password"));Library.require(p(q,"password").equals(p(q,"confirm_password")),"Passwords do not match.");DB.update("UPDATE users SET password_hash=? WHERE id=?",Security.hash(p(q,"password")),uid);}else DB.update("UPDATE users SET name=?,phone=?,address=? WHERE id=?",required(q,"name",180),required(q,"phone",40),required(q,"address",500),uid);go(q,r,"/profile","Your account has been updated.");return;}
  if(path.equals("/book-edit")){staffOnly(u);saveBook(q,u);go(q,r,"/manage?entity=books","Book and inventory saved.");return;}
  if(path.equals("/manage")){staffOnly(u);saveEntity(q,u);go(q,r,"/manage?entity="+p(q,"entity"),"Record saved.");return;}
  Library.require(path.equals("/action"),"Unknown action.");String action=p(q,"action");switch(action){
   case "read-notifications":DB.update("UPDATE notifications SET is_read=1 WHERE user_id=?"+(num(q,"id")>0?" AND id="+num(q,"id"):""),uid);go(q,r,"/notifications","Notifications marked as read.");return;
   case "copy-edit":case "copy-delete":staffOnly(u);Workflows.editCopy(uid,num(q,"id"),num(q,"branch_id"),p(q,"shelf"),branch(u),action.equals("copy-delete"));go(q,r,"/manage?entity=copies","Copy updated.");return;
   case "toggle":staffOnly(u);String entity=p(q,"entity");Library.require(ENTITIES.containsKey(entity)||Set.of("books","users").contains(entity),"Invalid record.");if(entity.equals("users")||entity.equals("branches"))adminOnly(u);if(entity.equals("users"))Library.require(num(q,"id")!=uid,"You cannot deactivate your own account.");DB.tx(c->{DB.update(c,"UPDATE "+entity+" SET active=CASE WHEN active=1 THEN 0 ELSE 1 END WHERE id=?",num(q,"id"));Library.audit(c,uid,"Toggle "+entity,"Record "+num(q,"id"));return null;});go(q,r,"/manage?entity="+entity,"Record status updated.");return;

   case "delete-record":staffOnly(u);String deleteEntity=p(q,"entity");Library.require(ENTITIES.containsKey(deleteEntity)||Set.of("books","users").contains(deleteEntity),"Invalid record.");if(deleteEntity.equals("users")||deleteEntity.equals("branches"))adminOnly(u);Library.require(!deleteEntity.equals("users")||num(q,"id")!=uid,"You cannot remove your own account.");try{DB.tx(c->{DB.update(c,"DELETE FROM "+deleteEntity+" WHERE id=?",num(q,"id"));Library.audit(c,uid,"Delete unused "+deleteEntity,"Record "+num(q,"id"));return null;});}catch(java.sql.SQLException ex){if("23000".equals(ex.getSQLState())||ex.getSQLState().startsWith("23"))throw new IllegalArgumentException("This record is linked to library history. Deactivate it instead.");throw ex;}go(q,r,"/manage?entity="+deleteEntity,"Unused record removed.");return;
   case "copy-status":staffOnly(u);DB.tx(c->{var copy=DB.one(c,"SELECT * FROM copies WHERE id=?",num(q,"id"));Library.require(copy!=null&&Set.of("AVAILABLE","MAINTENANCE","LOST","WITHDRAWN").contains(copy.get("status")),"Return or release this copy before changing its condition.");if(branch(u)!=null)Library.require(DB.id(copy,"branch_id")==branch(u),"Copy belongs to another branch.");String status=p(q,"status");Library.require(Set.of("AVAILABLE","MAINTENANCE","LOST","WITHDRAWN").contains(status),"Invalid copy condition.");DB.update(c,"UPDATE copies SET status=? WHERE id=?",status,copy.get("id"));Library.fulfill(c);Library.audit(c,uid,"Copy condition",copy.get("id")+" / "+status);return null;});go(q,r,"/manage?entity=copies","Copy condition updated.");return;
   default:throw new IllegalArgumentException("Unknown action.");
  }
 }
 private void saveBook(HttpServletRequest q,Map<String,Object> u)throws Exception{
  long id=num(q,"id");var old=id>0?DB.one("SELECT * FROM books WHERE id=?",id):null;Library.require(id==0||old!=null,"Book not found.");String title=required(q,"title",240),format=p(q,"format");Library.require(format.equals("PHYSICAL"),"Choose a book format.");BigDecimal fee=price(q,"fee");Library.require(format.equals("PHYSICAL")||fee.signum()>0,"Digital books require a fee greater than zero.");int days=positive(q,"duration_days",365);int year=positive(q,"publication_year",2100);String description=required(q,"description",4000);String edition=required(q,"edition",60);
  List<Path> created=new ArrayList<>();try{String cover=upload(q.getPart("cover"),false,created);String pdf=upload(q.getPart("pdf"),true,created);if(cover==null&&old!=null)cover=text(old,"cover_path");if(pdf==null&&old!=null)pdf=text(old,"pdf_path");Library.require(format.equals("PHYSICAL")||pdf!=null&&!pdf.isBlank(),"Upload a PDF for a digital book.");final String coverFile=cover==null||cover.isBlank()?null:cover;final String pdfFile=pdf==null||pdf.isBlank()?null:pdf;
   BookReferences.transaction(c->{String savedIsbn=required(q,"isbn",40);Library.require(DB.one(c,"SELECT id FROM books WHERE LOWER(isbn)=LOWER(?) AND id<>?",savedIsbn,id)==null,"This ISBN is already registered. Add copies to the existing book instead.");long saved=id;for(String t:List.of("authors","categories","publishers")){String key=t.equals("categories")?"category_id":t.substring(0,t.length()-1)+"_id";Library.require(DB.one(c,"SELECT id FROM "+t+" WHERE id=? AND active=1",num(q,key))!=null,"Select an active "+key+".");}
    if(id==0)saved=DB.update(c,"INSERT INTO books(title,isbn,author_id,category_id,publisher_id,description,publication_year,edition,format,fee,duration_days,cover_path,pdf_path,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",title,savedIsbn,num(q,"author_id"),num(q,"category_id"),num(q,"publisher_id"),description,year,edition,format,fee,days,coverFile,pdfFile,Library.now());else DB.update(c,"UPDATE books SET title=?,isbn=?,author_id=?,category_id=?,publisher_id=?,description=?,publication_year=?,edition=?,format=?,fee=?,duration_days=?,cover_path=?,pdf_path=? WHERE id=?",title,savedIsbn,num(q,"author_id"),num(q,"category_id"),num(q,"publisher_id"),description,year,edition,format,fee,days,coverFile,pdfFile,id);
    int copies=(int)num(q,"copies");Library.require(copies>=0&&copies<=500,"Add at most 500 copies at a time.");if(copies>0){Library.require(!format.equals("DIGITAL"),"Digital-only books cannot have physical copies.");long br=num(q,"branch_id");if(branch(u)!=null)Library.require(br==branch(u),"Select your assigned branch.");Library.require(DB.one(c,"SELECT id FROM branches WHERE id=? AND active=1",br)!=null,"Select an active branch.");for(int i=0;i<copies;i++)DB.update(c,"INSERT INTO copies(book_id,branch_id) VALUES(?,?)",saved,br);}Library.fulfill(c);Library.audit(c,DB.id(u,"id"),"Save book","Book "+saved);return null;});
  }catch(Exception ex){for(Path file:created)Files.deleteIfExists(file);throw ex;}
 }
 private String upload(Part part,boolean pdf,List<Path> created)throws Exception{if(part==null||part.getSize()==0)return null;Library.require(part.getSize()<=(pdf?50L*1024*1024:8L*1024*1024),pdf?"PDF must be under 50 MB.":"Cover must be under 8 MB.");Path folder=Config.data().resolve(pdf?"pdf":"covers");Files.createDirectories(folder);String name=UUID.randomUUID()+(pdf?".pdf":".jpg");Path dest=folder.resolve(name);if(pdf){try(InputStream in=part.getInputStream()){byte[] magic=in.readNBytes(5);Library.require(Arrays.equals(magic,"%PDF-".getBytes()),"Upload a valid PDF file.");}try(InputStream in=part.getInputStream()){Files.copy(in,dest);}created.add(dest);try(var document=org.apache.pdfbox.pdmodel.PDDocument.load(dest.toFile(),org.apache.pdfbox.io.MemoryUsageSetting.setupTempFileOnly())){Library.require(!document.isEncrypted()&&document.getNumberOfPages()>0,"Upload an unencrypted PDF with at least one page.");Library.require(document.getDocumentCatalog().getOpenAction()==null,"Remove automatic actions from the PDF before upload.");}}else{try(var imageInput=ImageIO.createImageInputStream(part.getInputStream())){var readers=ImageIO.getImageReaders(imageInput);Library.require(readers.hasNext(),"Upload a JPG or PNG cover.");var reader=readers.next();try{reader.setInput(imageInput);Library.require(Set.of("JPEG","PNG").contains(reader.getFormatName().toUpperCase(Locale.ROOT)),"Upload a JPG or PNG cover.");int w=reader.getWidth(0),h=reader.getHeight(0);Library.require(w>0&&h>0&&(long)w*h<=24000000,"Cover image is too large; use at most 24 megapixels.");BufferedImage img=reader.read(0);double scale=Math.min(1,1000.0/Math.max(w,h));BufferedImage out=new BufferedImage(Math.max(1,(int)(w*scale)),Math.max(1,(int)(h*scale)),BufferedImage.TYPE_INT_RGB);var g=out.createGraphics();g.setColor(java.awt.Color.WHITE);g.fillRect(0,0,out.getWidth(),out.getHeight());g.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION,java.awt.RenderingHints.VALUE_INTERPOLATION_BICUBIC);g.drawImage(img,0,0,out.getWidth(),out.getHeight(),null);g.dispose();ImageIO.write(out,"jpg",dest.toFile());created.add(dest);}finally{reader.dispose();}}}return name;}
 private void saveEntity(HttpServletRequest q,Map<String,Object> u)throws Exception{String entity=p(q,"entity");long id=num(q,"id");DB.tx(c->{
  if(id>0)Library.require(DB.one(c,"SELECT id FROM "+entity+" WHERE id=?",id)!=null,"Record not found.");
  if(ENTITIES.containsKey(entity)){if(entity.equals("branches"))adminOnly(u);Library.require(DB.one(c,"SELECT id FROM "+entity+" WHERE LOWER(name)=LOWER(?) AND id<>?",p(q,"name"),id)==null,"A record with this name already exists. Edit the existing record.");if(entity.equals("suppliers")&&!p(q,"email").isBlank())email(p(q,"email"));String[] fields=ENTITIES.get(entity);List<Object> values=new ArrayList<>();for(String field:fields){String value=p(q,field);if(entity.equals("branches")&&field.equals("address"))value=required(q,field,500);if(field.equals("name"))value=required(q,field,180);Library.require(value.length()<=(field.equals("description")?1000:field.equals("address")?500:field.equals("phone")?40:200),"Field is too long: "+field);values.add(value);}if(id==0)DB.update(c,"INSERT INTO "+entity+"("+String.join(",",fields)+") VALUES("+String.join(",",Collections.nCopies(fields.length,"?"))+")",values.toArray());else{values.add(id);DB.update(c,"UPDATE "+entity+" SET "+String.join(",",Arrays.stream(fields).map(f->f+"=?").toList())+" WHERE id=?",values.toArray());}}
  else if(entity.equals("purchases")||entity.equals("copies")){long br=num(q,"branch_id");if(branch(u)!=null)Library.require(br==branch(u),"Select your assigned branch.");int qty=positive(q,"quantity",500);Library.require(DB.one(c,"SELECT id FROM books WHERE id=? AND active=1 AND format<>'DIGITAL'",num(q,"book_id"))!=null,"Choose an active physical book.");Library.require(DB.one(c,"SELECT id FROM branches WHERE id=? AND active=1",br)!=null,"Choose an active branch.");if(entity.equals("purchases")){Library.require(DB.one(c,"SELECT id FROM suppliers WHERE id=? AND active=1",num(q,"supplier_id"))!=null,"Choose an active supplier.");DB.update(c,"INSERT INTO purchases(supplier_id,book_id,branch_id,quantity,unit_cost,created_at,invoice_ref,notes) VALUES(?,?,?,?,?,?,?,?)",num(q,"supplier_id"),num(q,"book_id"),br,qty,price(q,"unit_cost"),Library.now(),p(q,"invoice_ref"),p(q,"notes"));}else for(int i=0;i<qty;i++)DB.update(c,"INSERT INTO copies(book_id,branch_id) VALUES(?,?)",num(q,"book_id"),br);Library.fulfill(c);}
  else throw new IllegalArgumentException("Invalid workspace.");Library.audit(c,DB.id(u,"id"),"Save "+entity,"Record "+id);return null;});}
 private void file(HttpServletRequest q,HttpServletResponse r,Path folder,String name,String mime)throws Exception{Path path=folder.resolve(name).normalize();Library.require(path.startsWith(folder.normalize())&&Files.isRegularFile(path),"File is unavailable. Ask the library to replace it.");long size=Files.size(path),start=0,end=size-1;String range=q.getHeader("Range");if(range!=null&&range.matches("bytes=\\d+-\\d*")){String[] parts=range.substring(6).split("-",-1);start=Long.parseLong(parts[0]);if(!parts[1].isBlank())end=Math.min(end,Long.parseLong(parts[1]));if(start>end||start>=size){r.setStatus(416);r.setHeader("Content-Range","bytes */"+size);return;}r.setStatus(206);r.setHeader("Content-Range","bytes "+start+"-"+end+"/"+size);}r.setContentType(mime);r.setHeader("Accept-Ranges","bytes");r.setHeader("Content-Disposition","inline; filename=\""+(mime.equals("application/pdf")?"lumina-book.pdf":"cover.jpg")+"\"");r.setContentLengthLong(end-start+1);if(q.getMethod().equals("HEAD"))return;try(RandomAccessFile f=new RandomAccessFile(path.toFile(),"r")){f.seek(start);byte[] buf=new byte[32768];long left=end-start+1;while(left>0){int n=f.read(buf,0,(int)Math.min(buf.length,left));if(n<0)break;r.getOutputStream().write(buf,0,n);left-=n;}}}
}
